#!/bin/bash
# Generate PR verification report for GitHub PR comment
# Usage: ./scripts/generate-pr-report.sh <PR_NUMBER> <BACKEND_URL> <RESULTS_FILE>

set -e

PR_NUMBER="${1:?PR number required}"
BACKEND_URL="${2:-https://backend-affordabot-pr-${PR_NUMBER}.up.railway.app}"
RESULTS_FILE="${3:-artifacts/verification/pr-${PR_NUMBER}-results.json}"
REPORT_FILE="artifacts/verification/pr-${PR_NUMBER}-report.md"

# Ensure artifacts directory exists
mkdir -p artifacts/verification

# Parse results JSON if exists, otherwise use placeholder
if [ -f "$RESULTS_FILE" ]; then
    RESULTS=$(cat "$RESULTS_FILE")
else
    RESULTS='{"phases":[]}'
fi

# Generate timestamp
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Generate the report
cat > "$REPORT_FILE" << EOF
## 🔬 Verification Report for PR #${PR_NUMBER}

**Environment:** \`${BACKEND_URL}\`
**Timestamp:** ${TIMESTAMP}
**Branch:** \`$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo 'unknown')\`
**Commit:** \`$(git rev-parse --short HEAD 2>/dev/null || echo 'unknown')\`

### Results

| Phase | Status | Duration |
|-------|--------|----------|
EOF

# Parse results and add rows
# If results file exists with actual data, parse it
if [ -f "$RESULTS_FILE" ] && [ "$(cat $RESULTS_FILE | jq -r '.phases | length')" != "0" ] 2>/dev/null; then
    cat "$RESULTS_FILE" | jq -r '.phases[] | "| \(.name) | \(if .passed then "✅ PASS" else "❌ FAIL" end) | \(.duration)s |"' >> "$REPORT_FILE"
else
    # Use discovery report if available
    if [ -f "artifacts/verification/discovery/discovery_report.json" ]; then
        DISCOVERY=$(cat artifacts/verification/discovery/discovery_report.json)
        DB_STATUS=$(echo "$DISCOVERY" | jq -r 'if .results.db then "✅ PASS" else "❌ FAIL" end')
        PROMPT_STATUS=$(echo "$DISCOVERY" | jq -r 'if .results.prompt then "✅ PASS" else "❌ FAIL" end')
        QUERIES_STATUS=$(echo "$DISCOVERY" | jq -r 'if .results.queries then "✅ PASS" else "❌ FAIL" end')
        OVERALL=$(echo "$DISCOVERY" | jq -r 'if .passed then "✅ PASS" else "❌ FAIL" end')
        
        echo "| Discovery - DB | $DB_STATUS | - |" >> "$REPORT_FILE"
        echo "| Discovery - Prompt | $PROMPT_STATUS | - |" >> "$REPORT_FILE"
        echo "| Discovery - Queries | $QUERIES_STATUS | - |" >> "$REPORT_FILE"
    fi
    
    # Check for pipeline report
    if [ -f "artifacts/verification/affordabot_san_jose_pipeline_report.md" ]; then
        echo "| San Jose Pipeline | ✅ Report Generated | - |" >> "$REPORT_FILE"
    fi
fi

# Add summary section
cat >> "$REPORT_FILE" << 'EOF'

### Artifacts

<details>
<summary>📁 Generated Files</summary>

EOF

# List artifact files
ls -la artifacts/verification/ 2>/dev/null | tail -n +2 | while read line; do
    echo "- \`$line\`" >> "$REPORT_FILE"
done

cat >> "$REPORT_FILE" << 'EOF'

</details>

### Sign-Off Checklist

- [ ] All verification phases passed
- [ ] No visual regressions detected
- [ ] Performance acceptable
- [ ] Ready for merge

---

**Merge Command:**
```bash
EOF

echo "gh pr merge ${PR_NUMBER} --squash --delete-branch" >> "$REPORT_FILE"
echo '```' >> "$REPORT_FILE"
echo '' >> "$REPORT_FILE"
printf '<sub>Generated by `make verify-pr PR=%s`</sub>\n' "${PR_NUMBER}" >> "$REPORT_FILE"

echo "$REPORT_FILE"
