import os
from supabase import create_client, Client

url = os.environ.get("SUPABASE_URL")
key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")

if not url or not key:
    print("Error: Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY")
    exit(1)

supabase: Client = create_client(url, key)

sources = [
    {
        "jurisdiction_id": "san-jose",
        "url": "https://sanjose.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "San Jose Meetings Calendar",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {
            "document_type": "meeting_detail",
            "title": "San Jose Meeting Detail Calendar",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "san-jose",
        "url": "https://sanjose.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "San Jose Agendas",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {
            "document_type": "agenda",
            "title": "San Jose Agendas",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "san-jose",
        "url": "https://library.municode.com/ca/san_jose/codes/code_of_ordinances",
        "type": "code",
        "name": "San Jose Municipal Code",
        "status": "active",
        "source_method": "scrape",
        "handler": "municode",
        "metadata": {
            "document_type": "municipal_code",
            "title": "San Jose Municipal Code",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "san-jose",
        "url": "https://sanjose.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "San Jose Minutes",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {
            "document_type": "minutes",
            "title": "San Jose Minutes",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "san-jose",
        "url": "https://sanjose.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "San Jose Agenda Packets",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {
            "document_type": "agenda_packet",
            "title": "San Jose Agenda Packets",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "san-jose",
        "url": "https://sanjose.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "San Jose Attachments",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {
            "document_type": "attachment",
            "title": "San Jose Attachments",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "san-jose",
        "url": "https://sanjose.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "San Jose Staff Reports",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {
            "document_type": "staff_report",
            "title": "San Jose Staff Reports",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "santa-clara-county",
        "url": "https://sccgov.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Santa Clara County Meetings Calendar",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {
            "document_type": "meeting_detail",
            "title": "Santa Clara County Meeting Detail Calendar",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "santa-clara-county",
        "url": "https://sccgov.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Santa Clara County Agendas",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {
            "document_type": "agenda",
            "title": "Santa Clara County Agendas",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "santa-clara-county",
        "url": "https://sccgov.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Santa Clara County Minutes",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {
            "document_type": "minutes",
            "title": "Santa Clara County Minutes",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "santa-clara-county",
        "url": "https://sccgov.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Santa Clara County Agenda Packets",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {
            "document_type": "agenda_packet",
            "title": "Santa Clara County Agenda Packets",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "santa-clara-county",
        "url": "https://sccgov.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Santa Clara County Attachments",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {
            "document_type": "attachment",
            "title": "Santa Clara County Attachments",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "santa-clara-county",
        "url": "https://sccgov.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Santa Clara County Staff Reports",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {
            "document_type": "staff_report",
            "title": "Santa Clara County Staff Reports",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "saratoga",
        "url": "https://www.saratoga.ca.us/AgendaCenter",
        "type": "meetings",
        "name": "Saratoga Agenda Center",
        "status": "active",
        "source_method": "scrape",
        "handler": "agenda_center",
        "metadata": {
            "document_type": "agenda",
            "title": "Saratoga Agenda Center",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "saratoga",
        "url": "https://www.saratoga.ca.us/AgendaCenter",
        "type": "meetings",
        "name": "Saratoga Minutes",
        "status": "active",
        "source_method": "scrape",
        "handler": "agenda_center",
        "metadata": {
            "document_type": "minutes",
            "title": "Saratoga Minutes",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "saratoga",
        "url": "https://www.saratoga.ca.us/AgendaCenter",
        "type": "meetings",
        "name": "Saratoga Agenda Packets",
        "status": "active",
        "source_method": "scrape",
        "handler": "agenda_center",
        "metadata": {
            "document_type": "agenda_packet",
            "title": "Saratoga Agenda Packets",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "saratoga",
        "url": "https://www.saratoga.ca.us/AgendaCenter",
        "type": "meetings",
        "name": "Saratoga Attachments",
        "status": "active",
        "source_method": "scrape",
        "handler": "agenda_center",
        "metadata": {
            "document_type": "attachment",
            "title": "Saratoga Attachments",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "saratoga",
        "url": "https://www.saratoga.ca.us/AgendaCenter",
        "type": "meetings",
        "name": "Saratoga Staff Reports",
        "status": "active",
        "source_method": "scrape",
        "handler": "agenda_center",
        "metadata": {
            "document_type": "staff_report",
            "title": "Saratoga Staff Reports",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "sunnyvale",
        "url": "https://sunnyvaleca.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Sunnyvale Meetings Calendar",
        "status": "active",
        "source_method": "scrape",
        "handler": "sunnyvale_agendas",
        "metadata": {
            "document_type": "meeting_detail",
            "title": "Sunnyvale Meeting Detail Calendar",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "sunnyvale",
        "url": "https://sunnyvaleca.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Sunnyvale Agendas",
        "status": "active",
        "source_method": "scrape",
        "handler": "sunnyvale_agendas",
        "metadata": {
            "document_type": "agenda",
            "title": "Sunnyvale Agendas",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "sunnyvale",
        "url": "https://sunnyvaleca.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Sunnyvale Minutes",
        "status": "active",
        "source_method": "scrape",
        "handler": "sunnyvale_agendas",
        "metadata": {
            "document_type": "minutes",
            "title": "Sunnyvale Minutes",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "sunnyvale",
        "url": "https://sunnyvaleca.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Sunnyvale Agenda Packets",
        "status": "active",
        "source_method": "scrape",
        "handler": "sunnyvale_agendas",
        "metadata": {
            "document_type": "agenda_packet",
            "title": "Sunnyvale Agenda Packets",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "sunnyvale",
        "url": "https://sunnyvaleca.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Sunnyvale Attachments",
        "status": "active",
        "source_method": "scrape",
        "handler": "sunnyvale_agendas",
        "metadata": {
            "document_type": "attachment",
            "title": "Sunnyvale Attachments",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "cupertino",
        "url": "https://cupertino.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Cupertino Meetings Calendar",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {
            "document_type": "meeting_detail",
            "title": "Cupertino Meeting Detail Calendar",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "cupertino",
        "url": "https://cupertino.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Cupertino Agendas",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "agenda", "title": "Cupertino Agendas", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "cupertino",
        "url": "https://cupertino.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Cupertino Minutes",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "minutes", "title": "Cupertino Minutes", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "cupertino",
        "url": "https://cupertino.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Cupertino Agenda Packets",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "agenda_packet", "title": "Cupertino Agenda Packets", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "cupertino",
        "url": "https://cupertino.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Cupertino Attachments",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "attachment", "title": "Cupertino Attachments", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "cupertino",
        "url": "https://cupertino.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Cupertino Staff Reports",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "staff_report", "title": "Cupertino Staff Reports", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "mountain-view",
        "url": "https://mountainview.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Mountain View Meetings Calendar",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {
            "document_type": "meeting_detail",
            "title": "Mountain View Meeting Detail Calendar",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "mountain-view",
        "url": "https://mountainview.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Mountain View Agendas",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "agenda", "title": "Mountain View Agendas", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "mountain-view",
        "url": "https://mountainview.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Mountain View Minutes",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "minutes", "title": "Mountain View Minutes", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "mountain-view",
        "url": "https://mountainview.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Mountain View Agenda Packets",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "agenda_packet", "title": "Mountain View Agenda Packets", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "mountain-view",
        "url": "https://mountainview.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Mountain View Attachments",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "attachment", "title": "Mountain View Attachments", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "mountain-view",
        "url": "https://mountainview.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "Mountain View Staff Reports",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "staff_report", "title": "Mountain View Staff Reports", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "san-mateo-county",
        "url": "https://sanmateocounty.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "San Mateo County Meetings Calendar",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {
            "document_type": "meeting_detail",
            "title": "San Mateo County Meeting Detail Calendar",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "san-mateo-county",
        "url": "https://sanmateocounty.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "San Mateo County Agendas",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "agenda", "title": "San Mateo County Agendas", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "san-mateo-county",
        "url": "https://sanmateocounty.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "San Mateo County Minutes",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "minutes", "title": "San Mateo County Minutes", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "san-mateo-county",
        "url": "https://sanmateocounty.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "San Mateo County Agenda Packets",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "agenda_packet", "title": "San Mateo County Agenda Packets", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "san-mateo-county",
        "url": "https://sanmateocounty.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "San Mateo County Attachments",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "attachment", "title": "San Mateo County Attachments", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "san-mateo-county",
        "url": "https://sanmateocounty.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "San Mateo County Staff Reports",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "staff_report", "title": "San Mateo County Staff Reports", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "san-francisco-city-county",
        "url": "https://sfgov.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "San Francisco City County Meetings Calendar",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {
            "document_type": "meeting_detail",
            "title": "San Francisco City County Meeting Detail Calendar",
            "trust_tier": "official_partner",
        },
    },
    {
        "jurisdiction_id": "san-francisco-city-county",
        "url": "https://sfgov.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "San Francisco City County Agendas",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "agenda", "title": "San Francisco City County Agendas", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "san-francisco-city-county",
        "url": "https://sfgov.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "San Francisco City County Minutes",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "minutes", "title": "San Francisco City County Minutes", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "san-francisco-city-county",
        "url": "https://sfgov.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "San Francisco City County Agenda Packets",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "agenda_packet", "title": "San Francisco City County Agenda Packets", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "san-francisco-city-county",
        "url": "https://sfgov.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "San Francisco City County Attachments",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "attachment", "title": "San Francisco City County Attachments", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "san-francisco-city-county",
        "url": "https://sfgov.legistar.com/Calendar.aspx",
        "type": "meetings",
        "name": "San Francisco City County Staff Reports",
        "status": "active",
        "source_method": "scrape",
        "handler": "legistar_calendar",
        "metadata": {"document_type": "staff_report", "title": "San Francisco City County Staff Reports", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "campbell",
        "url": "https://www.campbellca.gov/AgendaCenter",
        "type": "meetings",
        "name": "Campbell Agendas",
        "status": "active",
        "source_method": "scrape",
        "handler": "agenda_center",
        "metadata": {"document_type": "agenda", "title": "Campbell Agendas", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "campbell",
        "url": "https://www.campbellca.gov/AgendaCenter",
        "type": "meetings",
        "name": "Campbell Minutes",
        "status": "active",
        "source_method": "scrape",
        "handler": "agenda_center",
        "metadata": {"document_type": "minutes", "title": "Campbell Minutes", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "campbell",
        "url": "https://www.campbellca.gov/AgendaCenter",
        "type": "meetings",
        "name": "Campbell Agenda Packets",
        "status": "active",
        "source_method": "scrape",
        "handler": "agenda_center",
        "metadata": {"document_type": "agenda_packet", "title": "Campbell Agenda Packets", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "campbell",
        "url": "https://www.campbellca.gov/AgendaCenter",
        "type": "meetings",
        "name": "Campbell Attachments",
        "status": "active",
        "source_method": "scrape",
        "handler": "agenda_center",
        "metadata": {"document_type": "attachment", "title": "Campbell Attachments", "trust_tier": "official_partner"},
    },
    {
        "jurisdiction_id": "campbell",
        "url": "https://www.campbellca.gov/AgendaCenter",
        "type": "meetings",
        "name": "Campbell Staff Reports",
        "status": "active",
        "source_method": "scrape",
        "handler": "agenda_center",
        "metadata": {"document_type": "staff_report", "title": "Campbell Staff Reports", "trust_tier": "official_partner"},
    },
]

for source in sources:
    try:
        # Check if exists
        existing = (
            supabase.table("sources")
            .select("id")
            .eq("jurisdiction_id", source["jurisdiction_id"])
            .eq("url", source["url"])
            .eq("name", source["name"])
            .execute()
        )
        if existing.data:
            print(f"Skipping {source['url']} (already exists)")
        else:
            data = supabase.table("sources").insert(source).execute()
            print(f"Inserted {source['url']}")
    except Exception as e:
        print(f"Error inserting {source['url']}: {e}")
